services:
  # Force redeploy - Backend service
  - type: web
    name: padelmate-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && cd backend && echo "Backend build completed successfully"
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: padelmate-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false

  - type: web
    name: padelmate-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://api.kingofthecourt.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: padelmate-db
    databaseName: padelmate
    user: padelmate_user
    plan: free 